#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: deluge

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    hashed_password: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: deluge
    state: absent

- name: Create deluge directory
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - /opt/deluge

- name: Create new downloads directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - "{{downloads.torrents}}/deluge"
    - "{{downloads.torrents}}/deluge/complete"
    - "{{downloads.torrents}}/deluge/incomplete"
    - "{{downloads.torrents}}/deluge/watched"
  when: (torrents_downloads_path is defined)|default(false)

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/deluge:/config"
      - "//home/{{user}}:/data:ro"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"

- name: Create and start container
  docker_container:
    name: deluge
    image: binhex/arch-delugevpn
    pull: yes
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      UMASK: "022"
      VPN_ENABLED: "no"
      VPN_USER:
      VPN_PASS:
      VPN_PROV:
      VPN_OPTIONS:
      STRICT_PORT_FORWARD: "yes"
      ENABLE_PRIVOXY: "no"
      LAN_NETWORK:
      NAME_SERVERS:
      DEBUG: "false"
    network_mode: "container:nordvpn"
    labels:
      traefik.enable: "true"
      traefik.backend: "deluge"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:deluge.{{domain}}"
      traefik.port: "8112"
      traefik.frontend.auth.basic: "{{ hashed_password }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    volumes: "{{ default_volumes + torrents_downloads_path|default([]) }}"
    purge_networks: yes
    restart_policy: always
    state: started

- name: Stop container to customize deluge settings
  docker_container:
    name: deluge
    state: stopped

- name: Check deluge label.conf exists
  stat:
    path: "/opt/deluge/label.conf"
    get_attributes: false
    get_checksum: false
    get_md5: false
    get_mime: false
  register: deluge_settings

- name: Import deluge settings
  copy:
    src: "{{item}}"
    dest: "/opt/deluge/{{item}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  with_items:
    - "autoadd.conf"
    - "blocklist.conf"
    - "core.conf"
    - "execute.conf"
    - "label.conf"
    - "web.conf"
  when: deluge_settings.stat.exists == False

- name: Start container to apply changes
  docker_container:
    name: deluge
    state: started