#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: firefox

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    hashed_password: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: firefox
    state: absent

- name: Create firefox directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/firefox

- name: Create and start container
  docker_container:
    name: firefox
    image: "jlesage/firefox"
    pull: yes
    published_ports:
      - "127.0.0.1:6000:5800"
    shm-size: 2g
    env:
      USER_ID: "{{uid}}"
      GROUP_ID: "{{gid}}"
      APP_NICENESS: "10"
    labels:
      traefik.enable: "true"
      traefik.backend: "firefox"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:firefox.{{domain}}"
      traefik.port: "5800"
      traefik.frontend.auth.basic: "{{ hashed_password }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    volumes:
      - "/opt/firefox:/config:rw"
    networks:
      - name: cloudbox
        aliases:
          - firefox
    purge_networks: yes
    restart_policy: always
    state: started