---
- hosts: localhost
  vars_files:
    - ['accounts.yml', 'accounts.yml.default']
    - ['settings.yml', 'settings.yml.default']
    - ['adv_settings.yml', 'adv_settings.yml.default']
  roles:
    - { role: sanity_check }
    - { role: pre_tasks }
    - { role: kernel, tags: ['kernel'], when: [ 'ansible_distribution_version == "16.04"' ] }
    - { role: backup, tags: ['backup'] }
    - { role: restore, tags: ['restore'] }
    - { role: pre_install, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: settings, tags: ['always', 'settings'] }
    - { role: user, tags: ['always'] }
    - { role: system, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'system'] }
    - { role: motd, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'motd'] }
    - { role: common, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'common'] }
    - { role: docker, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'docker'] }
    - { role: plexdrive, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: unionfs, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: rclone, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'rclone'] }
    - { role: scripts, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'scripts'] }
    - { role: traefik, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'traefik'] }
    - { role: netdata, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'netdata'] }
    - { role: nordvpn, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'nordvpn'] }
    - { role: plex, tags: ['cloudbox', 'mediabox', 'plex'] }
    - { role: tautulli, tags: ['cloudbox', 'mediabox', 'tautulli'] }
    - { role: plex_autoscan, tags: ['cloudbox', 'mediabox', 'plex_autoscan'] }
    - { role: plex_patrol, tags: ['cloudbox', 'mediabox', 'plex_patrol'] }
    - { role: plexlibrary, tags: ['cloudbox', 'mediabox', 'plexlibrary'] }
    - { role: portainer, tags: ['cloudbox', 'feederbox', 'portainer'] }
    - { role: cloudplow, tags: ['cloudbox', 'feederbox', 'cloudplow']}
    - { role: nzbget, tags: ['cloudbox', 'feederbox', 'nzbget'] }
    - { role: sabnzbd, tags: ['cloudbox', 'feederbox', 'sabnzbd'] }
    - { role: deluge, tags: ['cloudbox', 'feederbox', 'deluge'] }
    - { role: jackett, tags: ['cloudbox', 'feederbox', 'jackett'] }
    - { role: nzbhydra2, tags: ['cloudbox', 'feederbox', 'nzbhydra2'] }
    - { role: sonarr, tags: ['cloudbox', 'feederbox', 'sonarr'] }
    - { role: radarr, tags: ['cloudbox', 'feederbox', 'radarr'] }
    - { role: lidarr, tags: ['cloudbox', 'feederbox', 'lidarr'] }
    - { role: bazarr, tags: ['cloudbox', 'feederbox', 'bazarr'] }
    - { role: heimdall, tags: ['cloudbox', 'heimdall'] }
    - { role: ombi, tags: ['cloudbox', 'ombi'] }
    - { role: traktarr, tags: ['cloudbox', 'traktarr'] }
    - { role: plex_dupefinder, tags: ['cloudbox', 'plex_dupefinder'] }
    - { role: feeder_mount, tags: ['feeder-mount'] }
    - { role: feeder_dismount, tags: ['feeder-dismount'] }
    - { role: watchtower, tags: ['watchtower'] }
    - { role: sonarr4k, tags: ['sonarr4k'] }
    - { role: radarr4k, tags: ['radarr4k'] }
    - { role: radarrpq, tags: ['radarrpq'] }
    - { role: telly, tags: ['telly'] }
    - { role: handbrake, tags: ['handbrake'] }
    - { role: traktarrpq, tags: ['traktarrpq'] }
    - { role: traktarr4k, tags: ['traktarr4k'] }