---
- hosts: localhost
  vars_files:
    - ['settings.yml', 'settings.yml.default']
    - ['adv_settings.yml', 'adv_settings.yml.default']
  roles:
    - { role: sanity_check }
    - { role: pre_tasks }
    - { role: kernel, tags: ['kernel'], when: [ 'ansible_distribution_version == "16.04"' ] }
    - { role: settings, tags: ['always', 'settings'] }
    - { role: backup, tags: ['backup'] }
    - { role: restore, tags: ['restore'] }
    - { role: pre_install, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: system, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: motd, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'motd'] }
    - { role: common, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: unionfs, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: docker, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: plexdrive, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: rclone, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'rclone'] }
    - { role: scripts, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'scripts'] }
    - { role: traefik, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'traefik'] }
    - { role: plex, tags: ['cloudbox', 'mediabox', 'plex'] }
    - { role: tautulli, tags: ['cloudbox', 'mediabox', 'tautulli'] }
    - { role: ombi, tags: ['cloudbox', 'mediabox', 'ombi'] }
    - { role: plex_autoscan, tags: ['cloudbox', 'mediabox', 'plex_autoscan'] }
    - { role: portainer, tags: ['cloudbox', 'feederbox', 'portainer'] }
    - { role: cloudplow, tags: ['cloudbox', 'feederbox', 'cloudplow']}
    - { role: nzbget, tags: ['cloudbox', 'feederbox', 'nzbget'] }
    - { role: rutorrent, tags: ['cloudbox', 'feederbox', 'rutorrent'] }
    - { role: jackett, tags: ['cloudbox', 'feederbox', 'jackett'] }
    - { role: nzbhydra2, tags: ['cloudbox', 'feederbox', 'nzbhydra2'] }
    - { role: sonarr, tags: ['cloudbox', 'feederbox', 'sonarr'] }
    - { role: radarr, tags: ['cloudbox', 'feederbox', 'radarr'] }
    - { role: feeder_mount, tags: ['feeder-mount'] }
    - { role: feeder_dismount, tags: ['feeder-dismount'] }
    - { role: watchtower, tags: ['watchtower'] }
    - { role: lidarr, tags: ['lidarr'] }
    - { role: traktarr, tags: ['traktarr'] }
    - { role: plex_dupefinder, tags: ['plex_dupefinder'] }
    - { role: sonarr4k, tags: ['sonarr4k'] }
    - { role: radarr4k, tags: ['radarr4k'] }
    - { role: heimdall, tags: ['heimdall'] }
    - { role: netdata, tags: ['netdata'] }
    - { role: plex_patrol, tags: ['plex_patrol'] }
    - { role: telly, tags: ['telly'] }
    - { role: bazarr, tags: ['bazarr'] }
    - { role: sabnzbd, tags: ['sabnzbd'] }