---
- hosts: localhost
  vars_files:
    - ['accounts.yml', 'defaults/accounts.yml.default']
    - ['settings.yml', 'defaults/settings.yml.default']
    - ['adv_settings.yml', 'defaults/adv_settings.yml.default']
  roles:
    - { role: sanity_check }
    - { role: settings, tags: ['always', 'settings'] }
    - { role: pre_tasks }
    - { role: kernel, tags: ['kernel'] }
    - { role: pre_install, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: backup, tags: ['backup'] }
    - { role: restore, tags: ['restore'] }
    - { role: system, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'system'] }
    - { role: motd, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'motd'] }
    - { role: common, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'common'] }
    - { role: docker, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'docker'] }
    - { role: plexdrive, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: unionfs, tags: ['core', 'cloudbox', 'mediabox', 'feederbox'] }
    - { role: rclone, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'rclone'] }
    - { role: scripts, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'scripts'] }
    - { role: traefik, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'traefik'] }
    - { role: nordvpn, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'nordvpn'] }
    - { role: plex, tags: ['cloudbox', 'mediabox', 'plex'] }
    - { role: tautulli, tags: ['cloudbox', 'mediabox', 'tautulli'] }
    - { role: ombi, tags: ['cloudbox', 'mediabox', 'ombi'] }
    - { role: plex_autoscan, tags: ['cloudbox', 'mediabox', 'plex_autoscan'] }
    - { role: plex_patrol, tags: ['cloudbox', 'mediabox', 'plex_patrol'] }
    - { role: python-plexlibrary, tags: ['cloudbox', 'mediabox', 'python-plexlibrary'] }
    - { role: portainer, tags: ['cloudbox', 'portainer'] }
    - { role: organizr, tags: ['cloudbox', 'organizr'] }
    - { role: cloudplow, tags: ['cloudbox', 'feederbox', 'cloudplow'] }
    - { role: sabnzbd, tags: ['cloudbox', 'sabnzbd'], when: [ 'nzbs' ] }
    - { role: deluge, tags: ['cloudbox', 'deluge'], when: [ 'torrents' ] }
    - { role: jackett, tags: ['cloudbox', 'jackett'], when: [ 'torrents' ] }
    - { role: nzbhydra2, tags: ['cloudbox', 'nzbhydra2'], when: [ 'nzbs' ] }
    - { role: plex_dupefinder, tags: ['cloudbox', 'plex_dupefinder'] }    
    - { role: sonarr, tags: ['cloudbox', 'sonarr'] }
    - { role: radarr, tags: ['cloudbox', 'radarr'] }
    - { role: nzbget, tags: ['feederbox', 'nzbget'], when: [ 'nzbs' ] }
    - { role: rutorrent, tags: ['feederbox', 'rutorrent'], when: [ 'torrents' ] }
    - { role: feeder-mount, tags: ['feeder-mount'] }
    - { role: feeder-dismount, tags: ['feeder-dismount'] }
    - { role: handbrake, tags: ['handbrake'] }
    - { role: heimdall, tags: ['heimdall'] }
    - { role: netdata, tags: ['netdata'] }
    - { role: quassel, tags: ['quassel'] }
    - { role: lidarr, tags: ['lidarr'] }
    - { role: radarr4k, tags: ['radarr4k'] }
    - { role: radarrpq, tags: ['radarrpq'] }    
    - { role: sonarr4k, tags: ['sonarr4k'] }
    - { role: bazarr, tags: ['bazarr'] }
    - { role: telly, tags: ['telly'] }
    - { role: jackett_test, tags: ['jackett_test'] }
    - { role: thelounge, tags: ['thelounge'] }
    - { role: traktarr, tags: ['traktarr'] }
    - { role: traktarr4k, tags: ['traktarr4k'] }    
    - { role: traktarrpq, tags: ['traktarrpq'] }
    - { role: watchtower, tags: ['watchtower'] }
    - { role: znc, tags: ['znc'] }