#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: "Get video gid"
  shell: "getent group video  | cut -d: -f3"
  register: vgid

- name: "Set Variables"
  set_fact:
    uid: "{{uid.stdout}}"
    gid: "{{gid.stdout}}"
    vgid: "{{vgid.stdout}}"
