#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: watchtower
    state: absent

- name: Create container
  docker_container:
    name: watchtower
    image: "v2tec/watchtower"
    pull: yes
    command: sonarr radarr jackett nzbhydra2 nzbget sabnzbd tautulli ombi portainer watchtower traefik --cleanup --interval 15
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: cloudbox
        aliases:
          - watchtower
    purge_networks: yes
    state: stopped