#########################################################################
# Title:         Cloudbox: Watchower Role                               #
# Author(s):     L3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  v2tec/watchtower                                       #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: watchtower
    state: absent

- name: Create container
  docker_container:
    name: watchtower
    image: "v2tec/watchtower"
    pull: yes
    command: sonarr radarr lidarr jackett nzbhydra2 nzbget sabnzbd tautulli ombi organizr portainer watchtower traefik --cleanup --interval 15
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - watchtower
    purge_networks: yes
    state: stopped
