#########################################################################
# Title:         Cloudbox: NZBHydra2 Role                               #
# Author(s):     Desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: nzbhydra2-test

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: nzbhydra2
    state: absent

- name: Create nzbhydra2 directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/nzbhydra2

- name: Check if nzbhydra.yml exists
  stat:
    path: "/opt/nzbhydra2/NZBHydra2/nzbhydra.yml"
  register: nzbhydra2_yml

- name: Create and start container
  docker_container:
    name: nzbhydra2
    image: hotio/suitarr:nzbhydra2
    pull: yes
    published_ports:
      - "127.0.0.1:5076:5076"
    env:
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "nzbhydra2"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:nzbhydra2-test.{{domain}}"
      traefik.port: "5076"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nzbhydra2:/config"
      - "/opt/nzbhydra/hydra:/nzbhydra1"
    restart_policy: always
    networks:
      - name: cloudbox
        aliases:
          - nzbhydra2
    state: started

- name: Settings Tweaks
  include_tasks: "nzbhydra2_settings.yml"
  when: not (
        (nzbhydra2_yml.stat.exists)
        or
        ((continuous_integration|default(false,true))|bool)
    )
