#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: telly

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: "Assert that all Telly related settings are filled in."
  assert:
    that:
      - (telly.playlist is defined) and (telly.playlist is not none) and not (telly.playlist | trim == '') and (telly.playlist != "/opt/telly/file.m3u or URL2M3U")
      - (telly.streams is defined) and (telly.streams is not none) and not (telly.streams | trim == '')
    msg: "You must specify the Telly settings in 'adv_settings.yml'"

- name: Stop and remove any existing container
  docker_container:
    name: telly
    state: absent

- name: Create telly directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "/opt/telly"

- name: Create and start container
  docker_container:
    name: telly
    image: "tombowditch/telly"
    pull: yes
    network_mode: "container:nordvpn"
    env:
      PLAYLIST: "{{telly.playlist}}"
      STREAMS: "{{telly.streams}}"
      LISTEN: "0.0.0.0:6077"
      BASE: "telly:6077"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      USEREGEX: ".*UK.*"
      FRIENDLYNAME: TellyTuner
      DEVICEID: "12345678"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/telly:/opt/telly"
    restart_policy: always
    state: started
