#########################################################################
# Title:         Cloudbox: Netdata Role                                 #
# Author(s):     L3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  titpetric/netdata                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: netdata

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: netdata
    state: absent

- name: Create netdata directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/netdata
    - /opt/netdata/overrides

- name: Create and start container
  docker_container:
    name: netdata
    image: "titpetric/netdata:latest"
    pull: yes
    capabilities:
      - SYS_PTRACE
    published_ports:
      - "19999:19999"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "netdata"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:netdata.{{domain}}"
      traefik.port: "19999"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /opt/netdata/overrides:/etc/netdata/override
    networks:
      - name: cloudbox
        aliases:
          - netdata
    purge_networks: yes
    restart_policy: always
    state: started