#########################################################################
# Title:         Cloudbox: Netdata Role                                 #
# Author(s):     L3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  titpetric/netdata                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: netdata-test

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: netdata
    state: absent

- name: Create and start container
  docker_container:
    name: netdata
    image: "titpetric/netdata:latest"
    pull: yes
    capabilities:
      - SYS_PTRACE
    published_ports:
      - "127.0.0.1:19999:19999"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "netdata"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:netdata-test.{{domain}}"
      traefik.port: "19999"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: cloudbox
        aliases:
          - netdata
    restart_policy: always
    state: started
