#########################################################################
# Title:         Cloudbox: Lidarr Role                                  #
# Author(s):     L3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: lidarr

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: lidarr
    state: absent

- name: Create lidarr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/lidarr
    - /mnt/local/Media/Music

- name: Create and start container
  docker_container:
    name: lidarr
    image: hotio/suitarr:lidarr
    pull: yes
    published_ports:
      - "127.0.0.1:8686:8686"
    env:
      VERSION: "stable"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      BACKUP: "no"
    labels:
      traefik.enable: "true"
      traefik.backend: "lidarr"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:lidarr.{{domain}}"
      traefik.port: "8686"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/lidarr:/config"
      - "/mnt/unionfs/Media/Music:/music"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
      - "/mnt:/mnt"
      - "/opt/scripts:/scripts"
    networks:
      - name: cloudbox
        aliases:
          - lidarr
    restart_policy: always
    state: started
