#########################################################################
# Title:         Cloudbox: Rclone Role                                  #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Verify that Rclone version was specified
  fail: msg="You must specify the Rclone version in settings.yml"
  when: (
      (rclone.version is undefined)
      or
      (rclone.version is none)
      or
      (rclone.version | trim == '')
      )

- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present

- name: Create rclone directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - "/home/{{user}}/.config"
    - "/home/{{user}}/.config/rclone"
    - /opt/scripts/rclone

- name: Touch or create blank rclone.conf file
  file:
    path: "/home/{{user}}/.config/rclone/rclone.conf"
    state: touch
    mode: 0775
    owner: "{{user}}"
    group: "{{user}}"

- name: Cleanup rclone tmp path
  shell: rm -rf /tmp/rclone-*-linux-amd64
  args:
    warn: no

- name: Build version tag
  set_fact: rclone_version_tag="{{ ((rclone.version == 'latest') | ternary('current', 'v{{ "%.2f"|format(rclone.version) }}')) }}"

- name: "Unarchive rclone version: {{rclone_version_tag}}"
  unarchive:
    src: "https://downloads.rclone.org/{{ '' if rclone.version == 'latest' else rclone_version_tag + '/' }}rclone-{{ rclone_version_tag }}-linux-amd64.zip"
    dest: /tmp
    copy: no
    validate_certs: no

- name: Find rclone tmp dir
  shell: ls -d /tmp/rclone-*-linux-amd64
  register: rclone_tmp_dir

- name: Copy binary to /usr/bin/rclone
  copy:
    src: "{{ rclone_tmp_dir.stdout }}/rclone"
    dest: "/usr/bin/rclone"
    mode: 0755
    owner: root
    group: root

- name: Make dir for local manpages
  file:
    path: '/usr/local/share/man/man1'
    state: directory
    mode: 0775
    owner: root
    group: root

- name: Copy manpage
  copy:
    src: "{{ rclone_tmp_dir.stdout }}/rclone.1"
    dest: /usr/local/share/man/man1/rclone.1
    mode: 0644
    owner: root
    group: root

- name: Install manpage
  shell: mandb
  changed_when: false

- name: Get rclone version
  shell: rclone --version | head -n 1 | awk '{ print substr($2, 2, 4) }'
  register: rclone_version
  ignore_errors: yes

- name: "Display rclone version"
  debug:
    msg: "rclone version {{rclone_version.stdout}} installed."

- name: Import mount scripts
  copy:
    src: "{{item}}"
    dest: "/opt/scripts/rclone/{{item}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  with_items:
    - "mountlocal.sh"
    - "mountcloud.sh"

- name: Check mountlocal service exists
  stat:
    path: "/etc/systemd/system/mountlocal.service"
  register: mountlocal_service

- name: Stop existing mountlocal service
  systemd: state=stopped name=mountlocal
  when: mountlocal_service.stat.exists

- name: Import mountlocal.service
  template:
    src: mountlocal.service.js2
    dest: /etc/systemd/system/mountlocal.service
    force: yes
  when: mountlocal_service.stat.exists == False

- name: Check mountcloud service exists
  stat:
    path: "/etc/systemd/system/mountcloud.service"
  register: mountcloud_service

- name: Stop existing mountcloud service
  systemd: state=stopped name=mountcloud
  when: mountcloud_service.stat.exists

- name: Import mountcloud.service
  template:
    src: mountcloud.service.js2
    dest: /etc/systemd/system/mountcloud.service
    force: yes
  when: mountcloud_service.stat.exists == False
