#########################################################################
# Title:         Cloudbox: ruTorrent Role                               #
# Author(s):     L3uddz, Horjulf                                        #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  horjulf/rutorrent-autodl                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: rutorrent

- name: Stop and remove any existing container
  docker_container:
    name: rutorrent
    state: absent

- name: Create rutorrent directory
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - /opt/rutorrent
    - "{{downloads.torrents}}/rutorrent"
    - "{{downloads.torrents}}/rutorrent/completed"
    - "{{downloads.torrents}}/rutorrent/incoming"
    - "{{downloads.torrents}}/rutorrent/watched"

- name: Create and start container
  docker_container:
    name: rutorrent
    image: binhex/arch-rtorrentvpn
    pull: yes
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      VPN_ENABLED: "no"
      VPN_USER:
      VPN_PASS:
      VPN_PROV:
      VPN_OPTIONS:
      STRICT_PORT_FORWARD: "yes"
      ENABLE_PRIVOXY: "no"
      ENABLE_FLOOD: "yes"
      ENABLE_AUTODL_IRSSI: "yes"
      LAN_NETWORK:
      NAME_SERVERS:
      DEBUG: "false"
      PHP_TZ: "UTC"
      UMASK: "022"
    network_mode: "container:nordvpn"
    labels:
      traefik.enable: "true"
      traefik.backend: "rutorrent"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:rutorrent.{{domain}}"
      traefik.port: "9080"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/rutorrent:/config"
      - "{{downloads.torrents}}:/data"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "{{downloads.torrents}}/rutorrent:/downloads"
    purge_networks: yes
    restart_policy: always
    stop_timeout: 300
    state: started
