#########################################################################
# Title:         Cloudbox: ruTorrent Role                               #
# Author(s):     L3uddz, Horjulf                                        #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  horjulf/rutorrent-autodl                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: rutorrent

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    hashed_password: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: rutorrent
    state: absent

- name: Create rutorrent directory
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - /opt/rutorrent

- name: Create new downloads directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=yes"
  with_items:
    - "{{downloads.torrents}}/rutorrent"
    - "{{downloads.torrents}}/rutorrent/completed"
    - "{{downloads.torrents}}/rutorrent/incoming"
    - "{{downloads.torrents}}/rutorrent/watched"
  when: (torrents_downloads_path is defined)|default(false)

- name: Check if rtorrent.rc exists
  stat:
    path: "/opt/rutorrent/rtorrent/config/rtorrent.rc"
  register: rtorrent_rc

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/rutorrent:/config"
      - "/home/{{user}}:/data:ro"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"

- name: Create and start container
  docker_container:
    name: rutorrent
    image: binhex/arch-rtorrentvpn
    pull: yes
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      VPN_ENABLED: "no"
      VPN_USER:
      VPN_PASS:
      VPN_PROV:
      VPN_OPTIONS:
      STRICT_PORT_FORWARD: "yes"
      ENABLE_PRIVOXY: "no"
      ENABLE_FLOOD: "yes"
      ENABLE_AUTODL_IRSSI: "yes"
      LAN_NETWORK:
      NAME_SERVERS:
      DEBUG: "false"
      PHP_TZ: "UTC"
      UMASK: "022"
    network_mode: "container:nordvpn"
    labels:
      traefik.enable: "true"
      traefik.backend: "rutorrent"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:rutorrent.{{domain}}"
      traefik.port: "9080"
      traefik.frontend.auth.basic: "{{ hashed_password }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    volumes: "{{ default_volumes + torrents_downloads_path|default([]) }}"
    purge_networks: yes
    restart_policy: always
    stop_timeout: 300
    state: started

# Done for new setups (or setups requiring updating for updated rtorrent version).
- name: Standard Settings Tweaks
  include_tasks: "rutorrent_standard_settings.yml"
  when: (not continuous_integration)
        and
        ((not rtorrent_rc.stat.exists) or (standard_settings_needs_upgrading))

# Done for new setups (or setups requiring updating for updated rtorrent version).
- name: Subdir Settings Tweaks
  include_tasks: "rutorrent_subdir_settings.yml"
  when: (not continuous_integration)
        and
        ((not rtorrent_rc.stat.exists) or (standard_settings_needs_upgrading and subdirs_settings_exist))

- name: Start container to apply changes
  docker_container:
    name: rutorrent
    state: started
  when: (not continuous_integration)
        and
        ((not rtorrent_rc.stat.exists) or (standard_settings_needs_upgrading))
