#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: heimdall

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: heimdall
    state: absent

- name: Create heimdall directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/heimdall

- name: Create and start container
  docker_container:
    name: heimdall
    image: linuxserver/heimdall
    pull: yes
    published_ports:
      - "127.0.0.1:9443:443"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "heimdall"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:heimdall.{{domain}}"
      traefik.port: "9443"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/heimdall:/config"
    networks:
      - name: cloudbox
        aliases:
          - heimdall
    restart_policy: always
    state: started
