#########################################################################
# Title:         Cloudbox Community: Telly 2 Role                       #
# Author(s):     EnorMOZ, Desimaniac                                    #
# URL:           https://github.com/Cloudbox/Community                  #
# Docker Image:  tellytv/telly                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: telly2

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    hashed_password: "{{ hashed['content'] | b64decode }}"

- name: "Check if deluge exists"
  stat:
    path: "/opt/deluge/"
  register: deluge

- name: "Check if rutorrent exists"
  stat:
    path: "/opt/rutorrent/"
  register: rutorrent

- name: Set vpn fact
  set_fact:
    vpn: "deluge"
  when: (deluge.stat.exists) and (not rutorrent.stat.exists)

- name: Set vpn fact
  set_fact:
    vpn: "rutorrent"
  when: (rutorrent.stat.exists) and (not deluge.stat.exists)

- name: Stop and remove any existing container
  docker_container:
    name: telly2
    state: absent

- name: Create telly directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "/opt/telly2"
    - "/opt/telly2/telly.db"

- name: Create and start container
  docker_container:
    name: telly2
    image: "tellytv/telly:v1.5.0"
    pull: yes
    user: "{{uid}}:{{gid}}"
    command: --database.file="/telly/telly.db"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/telly2/telly.db:/telly/"
    env:
      TELLY_LOG_LEVEL: "debug"
    network_mode: "container:{{vpn}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "telly2"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:telly2.{{domain}}"
      traefik.port: "6077"
#      traefik.frontend.auth.basic: "{{ hashed_password }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    restart_policy: always
    state: started