#########################################################################
# Title:         Cloudbox: tautulli Role                                  #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  tautulli/tautulli                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: tautulli

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: tautulli
    state: absent

- name: Wait for Plex Logs folder to be created by Plex
  wait_for:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Logs"
    state: present

- name: Create tautulli directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/tautulli
    - /opt/scripts/tautulli

- name: Create and start container
  docker_container:
    name: tautulli
    image: tautulli/tautulli
    pull: yes
    published_ports:
      - "127.0.0.1:8181:8181"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "tautulli"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:tautulli.{{domain}}"
      traefik.port: "8181"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/tautulli:/config"
      - "/opt/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
      - "/opt/scripts:/scripts"
    restart_policy: always
    networks:
      - name: cloudbox
        aliases:
          - tautulli
    state: started
