#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: handbrake

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    hashed_password: "{{ hashed['content'] | b64decode }}"

- name: Install encoding tools
  apt: name="{{item}}" state=present update_cache=yes
  become: true
  with_items:
      - mediainfo
      - atomicparsley      

- name: Stop and remove any existing container
  docker_container:
    name: handbrake
    state: absent

- name: Create handbrake directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/handbrake
    - /mnt/local/handbrake
    - /mnt/local/handbrake/source
    - /mnt/local/handbrake/watch   
    - /mnt/local/handbrake/watch/24
    - /mnt/local/handbrake/watch/25
    - /mnt/local/handbrake/watch/26
    - /mnt/local/handbrake/watch/27
    - /mnt/local/handbrake/watch/28
    - /mnt/local/handbrake/output

- name: Create and start container
  docker_container:
    name: handbrake
    image: "jlesage/handbrake:latest"
    pull: yes
    published_ports:
      - "127.0.0.1:5800:5800"
    env:
      USER_ID: "{{uid}}"
      GROUP_ID: "{{gid}}"
      AUTOMATED_CONVERSION_PRESET: 24
      AUTOMATED_CONVERSION_PRESET_2: 25
      AUTOMATED_CONVERSION_PRESET_3: 26
      AUTOMATED_CONVERSION_PRESET_4: 27
      AUTOMATED_CONVERSION_PRESET_5: 28
      APP_NICENESS: "10"
    labels:
      traefik.enable: "true"
      traefik.backend: "handbrake"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:handbrake.{{domain}}"
      traefik.port: "5800"
      traefik.frontend.auth.basic: "{{ hashed_password }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    volumes:
      - "/opt/handbrake:/config:rw"
      - "/mnt/local/handbrake/watch/24:/watch:rw"
      - "/mnt/local/handbrake/watch/25:/watch2:rw"
      - "/mnt/local/handbrake/watch/26:/watch3:rw"
      - "/mnt/local/handbrake/watch/27:/watch4:rw"
      - "/mnt/local/handbrake/watch/28:/watch5:rw"
      - "/mnt/local/handbrake/output:/output:rw"
      - "/mnt/local/handbrake:/storage:ro"
    networks:
      - name: cloudbox
        aliases:
          - handbrake
    purge_networks: yes
    restart_policy: always
    state: started