#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: tautulli

- name: "Get user UID and GID"
  include_role:
    name: user

- name: Stop and remove any existing container
  docker_container:
    name: tautulli
    state: absent

- name: Create tautulli directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/tautulli

- name: Create and start container
  docker_container:
    name: tautulli
    image: hotio/suitarr:tautulli
    pull: yes
    published_ports:
      - "8181:8181"
    env:
      VERSION: "unstable"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      BACKUP: "no"
    labels:
      traefik.enable: "true"
      traefik.backend: "tautulli"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:tautulli.{{domain}}"
      traefik.port: "8181"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/tautulli:/config"
      - "/opt/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
      - "/opt/scripts:/scripts"
    networks:
      - name: cloudbox
        aliases:
          - tautulli
    purge_networks: yes
    restart_policy: always
    state: started