#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Gather list of running Docker containers
  shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' | xargs echo -n"
  register: docker_running_containers
  ignore_errors: yes
  when: docker_binary.stat.exists

- name: Stop all running Docker containers
  shell: "docker stop {{docker_running_containers.stdout}}"
  ignore_errors: yes
  when: (docker_binary.stat.exists) and not (docker_running_containers.stdout | trim == '')

- name: Remove all but selected list of containers
  docker_network:
    name: bridge
    connected:
      - traefik

- name: Restart all previously running Docker containers
  shell: 'docker start {{docker_running_containers.stdout}}'
  ignore_errors: yes
  when: (docker_binary.stat.exists) and not (docker_running_containers.stdout | trim == '')
