#########################################################################
# Title:         Cloudbox: Jackett Role                                 #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: jackett_test

- name: Slurp hashed htpasswd
  slurp:
    src: "/opt/traefik/.htpasswd"
  register: hashed

- name: Set hashed password
  set_fact:
    hashed_password: "{{ hashed['content'] | b64decode }}"

- name: Stop and remove any existing container
  docker_container:
    name: jackett_test
    state: absent

- name: Create jackett_test directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/jackett_test

- name: Create and start container
  docker_container:
    name: jackett_test
    image: hotio/suitarr:jackett
    pull: yes
    published_ports:
      - "127.0.0.1:9118:9117"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "jackett_test"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:jackett_test.{{domain}}"
      traefik.port: "9117"
      traefik.frontend.auth.basic: "{{ hashed_password }}"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/jackett_test:/config"
      - "/mnt/local/downloads:/downloads"
    networks:
      - name: cloudbox
        aliases:
          - jackett_test
    purge_networks: yes
    restart_policy: always
    state: started
