#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: "{{item}}"
  with_items:
    - "{{domain}}"
    - "www"
  when: organizr.direct_domain|default(false,true)

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: organizr

- name: "Get user UID and GID"
  include_role:
    name: user

- name: Stop and remove any existing container
  docker_container:
    name: organizr
    state: absent

- name: Create Organizr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/organizr

- name: Create and start container
  docker_container:
    name: organizr
    image: "tronyx/docker-organizr-v2:plex"
    pull: yes
    published_ports:
      - "7421:80"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "organizr"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:organizr.{{domain}}"
      traefik.port: "80"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/organizr:/config"
    networks:
      - name: cloudbox
        aliases:
          - organizr
    purge_networks: yes
    restart_policy: always
    state: started

- name: Wait for Organizr.css to be created
  wait_for:
    path: "/opt/organizr/www/Dashboard/css/themes/Organizr.css"
    state: present

- name: Download Plex Theme
  get_url:
    url:  "https://raw.githubusercontent.com/Burry/organizr-v2-plex-theme/master/css/Plex.css"
    dest: "/opt/organizr/www/Dashboard/css/themes/"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0664
    force: yes
    validate_certs: no
  ignore_errors: yes
