#########################################################################
# Title:         Cloudbox: RadarrSync Role                              #
# Author(s):     Desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create RadarrSync directories
  file: "path={{item}} state=directory owner={{user}} group={{user}} recurse=yes"
  with_items:
    - "/opt/radarrsync"

- name: Clone RadarrSync
  git:
    repo: "https://github.com/EnorMOZ/RadarrSync/"
    dest: /opt/radarrsync
    version: master
    force: yes
  become: yes
  become_user: "{{user}}"

- name: Check config exists
  stat:
    path: "/opt/radarrsync/Config.txt"
  register: radarrsync_config

- name: "Check if radarrpq exists"
  stat:
    path: "/opt/radarrpq/app/config.xml"
  register: radarrpq_config
  when: not radarrsync_config.stat.exists

- name: "When radarrpq exists, add api key to radarrsync config"
  block:

  - name: Pull radarrpq api key
    xml:
      path: "/opt/radarrpq/app/config.xml"
      xpath: /Config/ApiKey
      content: text
    register: xmlapi

  - name: Pull radarrpq port
    xml:
      path: "/opt/radarrpq/app/config.xml"
      xpath: /Config/Port
      content: text
    register: xmlport

  - name: Set radarrpq facts
    set_fact:
      radarrpq_api_key: "{{ xmlapi.matches[0].ApiKey }}"
      radarrpq_profile: "Any"
      radarrpq_port: "{{ xmlport.matches[0].Port }}"
      radarrpq_root: "Poor Quality"

  when: (not radarrsync_config.stat.exists) and (radarrpq_config.stat.exists)

- name: "Check if radarr exists"
  stat:
    path: "/opt/radarr/app/config.xml"
  register: radarr_config
  when: not radarrsync_config.stat.exists

- name: "When radarr exists, add api key to radarrsync config"
  block:

  - name: Pull radarr api key
    xml:
      path: "/opt/radarr/app/config.xml"
      xpath: /Config/ApiKey
      content: text
    register: xmlapi

  - name: Pull radarr port
    xml:
      path: "/opt/radarr/app/config.xml"
      xpath: /Config/Port
      content: text
    register: xmlport

  - name: Set radarr facts
    set_fact:
      radarr_api_key: "{{ xmlapi.matches[0].ApiKey }}"
      radarr_profile: "HD-1080p"
      radarr_port: "{{ xmlport.matches[0].Port }}"
      radarr_root: "YIFY"

  when: (not radarrsync_config.stat.exists) and (radarr_config.stat.exists)

- name: Import default config
  template:
    src: "config.json.js2"
    dest: "/opt/radarrsync/Config.txt"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  when: not radarrsync_config.stat.exists

- name: Set RadarrSync.py as executable
  file:
    path: /opt/radarrsync/RadarrSync.py
    owner: "{{user}}"
    group: "{{user}}"
    mode: a+x

- name: Set directory permissions
  file: "path=/opt/radarrsync state=directory owner={{user}} group={{user}} recurse=yes"

- name: "Create /usr/local/bin symlink"
  file:
    src: "/opt/radarrsync/RadarrSync.py"
    dest: "/usr/local/bin/radarrsync"
    state: link

- name: Import radarrsync scripts
  template:
    src: "{{item}}"
    dest: "/opt/scripts/system/{{item}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  with_items:
    - "slack_radarrsync.sh"
    - "radarrsync-report.sh"

- name: "Schedule cron task for daily update."
  cron:
    name: "RadarrSync4K"
    user: "{{user}}"
    job: "/opt/scripts/radarrsync/radarrsync_report.sh"
    special_time: daily
    state: present