#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: nzbget

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: nzbget
    state: absent

- name: Create nzbget directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/nzbget
    - "{{downloads.nzbs}}/nzbget"

- name: Check subfolder1 exists
  stat:
    path: /opt/nzbget/NZBGet
  register: subfolder1

- name: Check subfolder2 exists
  stat:
    path: /opt/nzbget/app
  register: subfolder2

- name: Move 'nzbget' folder contents to 'app' subfolder
  shell: |
    mv /opt/nzbget /tmp/app
    mkdir /opt/nzbget
    mv /tmp/app /opt/nzbget/
    find /opt/nzbget/* -type d -empty -delete
    chown -R {{user}}:{{user}} /opt/nzbget
  when: not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Move 'NZBGet' subfolder to 'app' subfolder
  shell: |
    mv /opt/nzbget/NZBGet /opt/nzbget/app
    chown -R {{user}}:{{user}} /opt/nzbget
  when: (subfolder1.stat.exists) and (not subfolder2.stat.exists)

- name: Check nzbget.conf exists
  stat:
    path: "/opt/nzbget/app/nzbget.conf"
  register: nzbget_conf

- name: Create and start container
  docker_container:
    name: nzbget
    image: hotio/suitarr:nzbget
    pull: yes
    published_ports:
      - "6789:6789"
    env:
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "nzbget"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:nzbget.{{domain}}"
      traefik.port: "6789"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nzbget:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "{{downloads.nzbs}}/nzbget:/downloads/nzbs/nzbget"
    restart_policy: always
    networks:
      - name: cloudbox
        aliases:
          - nzbget
    state: started

- name: Settings Tweaks
  include_tasks: "nzbget_settings.yml"
  when: not (
        (nzbget_conf.stat.exists)
        or
        ((continuous_integration|default(false,true))|bool)
    )
