#########################################################################
# Title:         Cloudbox: Sonarr Role                                  #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: sonarr-test

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: sonarr
    state: absent

- name: Create sonarr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/sonarr

- name: Create and start container
  docker_container:
    name: sonarr
    image: "hotio/suitarr:sonarr"
    pull: yes
    published_ports:
      - "127.0.0.1:8989:8989"
    env:
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "sonarr"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:sonarr-test.{{domain}}"
      traefik.port: "8989"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/sonarr:/config"
      - "/mnt/unionfs/Media/TV:/tv"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{sabnzbd.downloads}}:/downloads/sabnzbd"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
      - "{{deluge.downloads}}:/downloads/deluge"
      - "/mnt:/mnt"
      - "/opt/scripts:/scripts"
    networks:
      - name: cloudbox
        aliases:
          - sonarr
    restart_policy: always
    state: started
