#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: portainer

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: portainer
    state: absent

- name: Create portainer directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/portainer

- name: Create and start container
  docker_container:
    name: portainer
    image: "portainer/portainer"
    pull: yes
    published_ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:portainer.{{domain}}"
      traefik.port: "9000"
      traefik.docker.network: "cloudbox"
    networks:      
      - name: cloudbox
        aliases:
          - portainer
    restart_policy: always
    state: started
