#########################################################################
# Title:         Cloudbox: Portainer Role                               #
# Author(s):     L3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  portainer/portainer                                    #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: portainer-test

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: portainer
    state: absent

- name: Create portainer directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/portainer

- name: Create and start container
  docker_container:
    name: portainer
    image: "portainer/portainer"
    pull: yes
    published_ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:portainer-test.{{domain}}"
      traefik.port: "9000"
      traefik.docker.network: "cloudbox"
    networks:
      - name: cloudbox
        aliases:
          - portainer
    restart_policy: always
    state: started
