#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get IP Address
  ipinfoio_facts:

- name: "Cloudflare: Add '{{cloudbox_type}}' subdomain to '{{domain}}'"
  include_role:
    name: cloudflare
  vars:
    subdomain: "{{cloudbox_type}}"
