#########################################################################
# Title:         Cloudbox: Pre-Tasks Role - User Task                   #
# Author(s):     Desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if user '{{user}}' exists"
  shell: "id -un {{user}} >/dev/null 2>&1;"
  register: user_check
  failed_when: user_check.rc > 1

- block:

  - name: "Get '{{user}}' info"
    user:
      name: "{{user}}"
    register: user_info

  - name: "Set 'uid', 'gid', and 'vgid'"
    set_fact:
      uid: "{{ user_info.uid }}"
      gid: "{{ user_info.group }}"
      vgid: "{{ lookup('pipe','getent group video | cut -d: -f3') }}"

  when: user_check.rc == 0
