#########################################################################
# Title:         Cloudbox: Pre-Tasks - Variables Task                   #
# Author(s):     Desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Needed again for cloudbox_mod.
- name: "Set 'continuous_integration' variable"
  set_fact:
    continuous_integration: "{{ continuous_integration | default(false,true) }}"

- name: "Set 'ssl_enabled' variable"
  set_fact:
    ssl_enabled: "{{ true if not(
        (ssl.dns is undefined)
        or
        (ssl.dns is none)
        or
        (ssl.dns | trim == '')
      )
      else false }}"

- name: "Set 'cloudflare_enabled' variable"
  set_fact:
    cloudflare_enabled: "{{ true if not(
        (cloudflare_api_token is undefined)
        or
        (cloudflare_api_token is none)
        or
        (cloudflare_api_token | trim == '')
      )
      else false }}"

- name: "Set 'rclone_enabled' variable"
  set_fact:
    rclone_enabled: "{{ true if not(
        (rclone.config is undefined)
        or
        (rclone.config is none)
        or
        (rclone.config | trim == '')
      )
      else false }}"

- name: "Set 'localhost_ip' variable"
  set_fact:
    localhost_ip: "127.0.0.1"

- name: "Set 'plex_account_enabled' variable"
  set_fact:
    plex_account_enabled: "{{ true if not(
        (plex is undefined)
        or
        (plex is none)
        or
        (plex | trim == '')
        or
        (plex.user is undefined)
        or
        (plex.user is none)
        or
        (plex.user | trim == '')
        or
        (plex.pass is undefined)
        or
        (plex.pass is none)
        or
        (plex.pass | trim == '')
      )
      else false }}"

- name: "Set 'slack_enabled' variable"
  set_fact:
    slack_enabled: "{{ true if not(
        (slack.token is undefined)
        or
        (slack.token is none)
        or
        (slack.token | trim == '')
        )
      or not(
        (slack is undefined)
        or
        (slack is none)
        or
        (slack | trim == '')
        or
        (slack.token is undefined)
        or
        (slack.token is none)
        or
        (slack.token | trim == '')
      )
      else false }}"

- name: "Set 'nzbs_downloads_path' variable"
  set_fact:
    nzbs_downloads_path:
      - "{{downloads.nzbs}}:/downloads/nzbs"
  when: not (
        (downloads is undefined)
        or
        (downloads is none)
        or
        (downloads | trim == '')
        or
        (downloads.nzbs is undefined)
        or
        (downloads.nzbs is none)
        or
        (downloads.nzbs | trim == '')
      )

- name: "Set 'torrents_downloads_path' variable"
  set_fact:
    torrents_downloads_path:
      - "{{downloads.torrents}}:/downloads/torrents"
  when: not (
        (downloads is undefined)
        or
        (downloads is none)
        or
        (downloads | trim == '')
        or
        (downloads.torrents is undefined)
        or
        (downloads.torrents is none)
        or
        (downloads.torrents | trim == '')
      )

- name: "Set 'nzbs' role tag"
  set_fact:
    nzbs: "{{ true if (
        (nzbs_downloads_path is defined|default(false,true))
        )
        else false }}"

- name: "Set 'torrents' role tag"
  set_fact:
    torrents: "{{ true if (
        (torrents_downloads_path is defined|default(false,true))
        )
        else false }}"
