#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: radarrpq

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: radarrpq
    state: absent

- name: Create radarrpq directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/radarrpq

- name: Check subfolder1 exists
  stat:
    path: /opt/radarrpq/Radarr
  register: subfolder1

- name: Check subfolder2 exists
  stat:
    path: /opt/radarrpq/app
  register: subfolder2

- name: Move 'radarrpq' folder contents to 'app' subfolder
  shell: |
    mv /opt/radarrpq /tmp/app
    mkdir /opt/radarrpq
    mv /tmp/app /opt/radarrpq/
    find /opt/radarrpq/* -type d -empty -delete
    chown -R {{user}}:{{user}} /opt/radarrpq
  when: not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Move 'Radarr' subfolder to 'app' subfolder
  shell: |
    mv /opt/radarrpq/Radarr /opt/radarrpq/app
    chown -R {{user}}:{{user}} /opt/radarrpq
  when: (subfolder1.stat.exists) and (not subfolder2.stat.exists)

- name: Create and start container
  docker_container:
    name: radarrpq
    image: hotio/suitarr:radarr
    pull: yes
    published_ports:
      - "7880:7878"
    env:
      VERSION: "unstable"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      BACKUP: "no"
    labels:
      traefik.enable: "true"
      traefik.backend: "radarrpq"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:radarrpq.{{domain}}"
      traefik.port: "7880"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/radarrpq:/config"
      - /mnt/unionfs/Media:/data
      - "/mnt/unionfs/Media/Poor Quality:/movies"
      - "/mnt:/mnt"
      - "/opt/scripts:/scripts"
      - "{{downloads.nzbs}}:/downloads/nzbs"
      - "{{downloads.torrents}}:/downloads/torrents"
    networks:
      - name: cloudbox
        aliases:
          - radarrpq
    restart_policy: always
    state: started
