---
- name: Get IP Address
  ipinfoio_facts:

- name: Create user SSL directory
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /home/{{user}}/.docker

- name: Run SSL container to create client certificates
  docker_container:
    name: ssl
    image: paulczar/omgwtfssl
    pull: yes
    volumes:
      - /home/{{user}}/.docker:/certs
    state: absent

- name: "Wait for 10 seconds for certificates to be created"
  wait_for:
    timeout: 10