#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Stop Container
- name: Wait for ServerConfig.json to be created
  wait_for:
    path: "/opt/jackett/app/ServerConfig.json"
    state: present

- name: "Wait for 10 seconds before stopping jackett container"
  wait_for:
    timeout: 10

- name: Stop container to customize ServerConfig.json
  docker_container:
    name: jackett
    state: stopped

- name: Set password for jackett
  lineinfile:
    path: "/opt/jackett/app/ServerConfig.json"
    regexp: '^AdminPassword\s?:.*'
    line: '"AdminPassword": "{{passwd}}"'
    state: present

# Start Container
- name: Start container to apply changes
  docker_container:
    name: jackett
    state: started