#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: jackett

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: jackett
    state: absent

- name: Create jackett directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/jackett

- name: Check subfolder1 exists
  stat:
    path: /opt/jackett/Jackett
  register: subfolder1

- name: Check subfolder2 exists
  stat:
    path: /opt/jackett/app
  register: subfolder2

- name: Move 'jackett' folder contents to 'app' subfolder
  shell: |
    mv /opt/jackett /tmp/app
    mkdir /opt/jackett
    mv /tmp/app /opt/jackett/
    find /opt/jackett/* -type d -empty -delete
    chown -R {{user}}:{{user}} /opt/jackett
  when: not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Move 'Jackett' subfolder to 'app' subfolder
  shell: |
    mv /opt/jackett/Jackett /opt/jackett/app
    chown -R {{user}}:{{user}} /opt/jackett
  when: (subfolder1.stat.exists) and (not subfolder2.stat.exists)

- name: Create and start container
  docker_container:
    name: jackett
    image: hotio/suitarr:jackett
    pull: yes
    published_ports:
      - "9117:9117"
    env:
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "jackett"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:jackett.{{domain}}"
      traefik.port: "9117"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/jackett:/config"
    networks:
      - name: cloudbox
        aliases:
          - jackett
    restart_policy: always
    state: started

- name: Remove bridge network
  shell: "docker network disconnect -f bridge jackett"
  ignore_errors: yes

- name: Restart container to apply network changes
  docker_container:
    name: jackett
    state: restarted