#########################################################################
# Title:         Cloudbox: The Lounge Role                              #
# Author(s):     L3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: thelounge

- name: Stop and remove any existing container
  docker_container:
    name: thelounge
    state: absent

- name: Create thelounge directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/thelounge

- name: Create and start container
  docker_container:
    name: thelounge
    image: "linuxserver/thelounge"
    pull: yes
    published_ports:
      - "127.0.0.1:9500:9000"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "lounge"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:lounge.{{domain}}"
      traefik.port: "9000"
      traefik.docker.network: "cloudbox"
      "com.github.cloudbox.cloudbox_managed": "true"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/thelounge:/config"
    networks:
      - name: cloudbox
        aliases:
          - thelounge
    purge_networks: yes
    restart_policy: always
    state: started
