#########################################################################
# Title:         Cloudbox: SABnzbd Role                                 #
# Author(s):     Desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: sabnzbd

- name: "Get user UID and GID"
  include_role:
    name: user

- name: Stop and remove any existing container
  docker_container:
    name: sabnzbd
    state: absent

- name: Create sabnzbd directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/sabnzbd
    - "{{downloads.nzbs}}/sabnzbd"
    - "{{downloads.nzbs}}/sabnzbd/complete"
    - "{{downloads.nzbs}}/sabnzbd/incomplete"
    - "{{downloads.nzbs}}/sabnzbd/watched"
    - "{{downloads.nzbs}}/sabnzbd/logs"

- name: Check sabnzbd.ini exists
  stat:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
  register: sabnzbd_ini

- name: Create and start container
  docker_container:
    name: sabnzbd
    image: hotio/suitarr:sabnzbd
    pull: yes
    published_ports:
      - "8081:8080"
    env:
      VERSION: "stable"
      BACKUP: "no"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "sabnzbd"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:sabnzbd.{{domain}}"
      traefik.port: "8080"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/sabnzbd:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "{{downloads.nzbs}}/sabnzbd:/downloads/nzbs/sabnzbd"
    networks:
      - name: cloudbox
        aliases:
          - sabnzbd
    purge_networks: yes
    restart_policy: always
    state: started

- name: Settings Tweaks
  include_tasks: "sabnzbd_settings.yml"
  when: not (
        (sabnzbd_ini.stat.exists)
        or
        ((continuous_integration|default(false,true))|bool)
    )
