#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Stop Container
- name: Wait for sabnzbd.ini to be created
  wait_for:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    state: present

- name: "Wait for 10 seconds before stopping sabnzbd container"
  wait_for:
    timeout: 10

- name: Stop container to customize sabnzbd.ini
  docker_container:
    name: sabnzbd
    state: stopped

- name: Add domain to whitelist
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '(^host_whitelist\s?=.*,)'
    backrefs: yes
    line: '\1 sabnzbd.{{domain}}'
    state: present

- name: Remove url_base
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^url_base\s?=.*'
    line: 'url_base = ""'
    state: present

# Authentication
- name: Set Username
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    insertafter: '^warn_dupl_jobs\s?=.*'
    regexp: '^username\s?=.*'
    line: "username = {{user}}"
    state: present

- name: Set Password
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    insertafter: '^rss_filenames\s?=.*'
    regexp: '^password\s?=.*'
    line: "password = {{sabnzbd.passwd}}"
    state: present

- name: Set Form Auth
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^html_login\s?=.*'
    line: 'html_login = 1'
    state: present

# Paths
- name: Change incomplete downloads directory
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^download_dir\s?=.*'
    line: 'download_dir = /downloads/nzbs/sabnzbd/incomplete'
    state: present

- name: Change complete downloads directory
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^complete_dir\s?=.*'
    line: 'complete_dir = /downloads/nzbs/sabnzbd/complete'
    state: present

- name: Change watched directory
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^dirscan_dir\s?=.*'
    line: 'dirscan_dir = /downloads/nzbs/sabnzbd/watched'
    state: present

- name: Change script directory
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^script_dir\s?=.*'
    line: 'script_dir = /scripts'
    state: present

- name: Change logs directory
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^log_dir\s?=.*'
    line: 'log_dir = /downloads/nzbs/sabnzbd/logs'
    state: present

# Tweaks
- name: Change theme
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^web_color\s?=.*'
    line: 'web_color = Night'
    state: present

- name: Change skin
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^notified_new_skin\s?=.*'
    line: 'notified_new_skin = 2'
    state: present

- name: Set permissions
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^permissions\s?=.*'
    line: 'permissions = 755'
    state: present

- name: Set minimum free space
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^download_free\s?=.*'
    line: 'download_free = 20G'
    state: present

- name: Ignore samples
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^ignore_samples\s?=.*'
    line: 'ignore_samples = 1'
    state: present

- name: Set direct unpack
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^direct_unpack\s?=.*'
    line: 'direct_unpack = 1'
    state: present

- name: Set url base
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^url_base\s?=.*'
    line: 'url_base = /sabnzbd'
    state: present

- name: Set new nzb on failure
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^new_nzb_on_failure\s?=.*'
    line: 'new_nzb_on_failure = 1'
    state: present

- name: Set unwanted extensions
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^unwanted_extensions\s?=.*'
    line: 'unwanted_extensions = exe, com, bat, sh'
    state: present

- name: Set pause_on_pwrar
  lineinfile:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    regexp: '^pause_on_pwrar\s?=.*'
    line: 'pause_on_pwrar = 2'
    state: present

# Start Container
- name: Start container to apply changes
  docker_container:
    name: sabnzbd
    state: started