#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if '{{item}}' exists."
  stat:
    path: "{{playbook_dir}}/{{item}}"
  register: file

- name: "Copy '{{item}}.default' to '{{item}}'."
  copy:
    src: "{{playbook_dir}}/{{item}}.default"
    dest: "{{playbook_dir}}/{{item}}"
    owner: "{{cloudbox_yml.stat.uid}}"
    group: "{{cloudbox_yml.stat.gid}}"
    mode: 0664
    force: yes
  when: not file.stat.exists

- name: "Get stats on '{{item}}' for hash check."
  stat:
    path: "{{playbook_dir}}/{{item}}"
  register: file

# Hash Check
- name: "Get stats on '{{item}}.default' for hash check."
  stat:
    path: "{{playbook_dir}}/{{item}}.default"
  register: file_default
  when: item == 'accounts.yml'

# Hash Check
- name: "Ensure '{{item}}' does not match '{{item}}.default'."
  assert:
    that:
      - file.stat.exists
      - file.stat.checksum != file_default.stat.checksum
    msg: "You have not edited your '{{item}}' file, yet. Please fill in your settings and retry. For more info, see the Wiki page 'Install: Settings'."
  when: item == 'accounts.yml'

- name: "Encrypting '{{item}}'" 
  shell: "ansible-vault encrypt {{item}}"
  become: yes
  become_user: "{{cloudbox_yml.stat.pw_name}}"