#########################################################################
# Title:         Cloudbox: Ombi Role                                    #
# Author(s):     RXWatcher1, L3uddz, Desimaniac                         #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: "{{ ombi.subdomain|default('ombi',true) }}"

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: ombi
    state: absent

- name: Create ombi directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/ombi

- name: Create and start container
  docker_container:
    name: ombi
    image: "linuxserver/ombi"
    pull: yes
    published_ports:
      - "127.0.0.1:3579:3579"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "ombi"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:ombi.{{domain}}"
      traefik.port: "3579"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/ombi:/config"
    networks:
      - name: cloudbox
        aliases:
          - ombi
    restart_policy: always
    state: started
