#########################################################################
# Title:         Cloudbox: Radarr4K Role                                #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: radarr4k-test

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: radarr4k
    state: absent

- name: Create radarr4k directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/radarr4k

- name: Create and start container
  docker_container:
    name: radarr4k
    image: hotio/suitarr:radarr
    pull: yes
    published_ports:
      - "127.0.0.1:7879:7878"
    env:
      VERSION: "unstable"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      BACKUP: "no"
    labels:
      traefik.enable: "true"
      traefik.backend: "radarr4k"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:radarr4k-test.{{domain}}"
      traefik.port: "7878"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/radarr4k:/config"
      - "/mnt/unionfs/Media/Movies:/movies"
      - "{{nzbget.downloads}}:/downloads/nzbget"
      - "{{sabnzbd.downloads}}:/downloads/sabnzbd"
      - "{{rutorrent.downloads}}:/downloads/rutorrent"
      - "{{deluge.downloads}}:/downloads/deluge"
      - "/mnt:/mnt"
      - "/opt/scripts:/scripts"
    networks:
      - name: cloudbox
        aliases:
          - radarr4k
    restart_policy: always
    state: started
