#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: radarr4k

- name: "Get user UID and GID"
  include_role:
    name: user
    
- name: Stop and remove any existing container
  docker_container:
    name: radarr4k
    state: absent

- name: Create radarr4k directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/radarr4k

- name: Check subfolder1 exists
  stat:
    path: /opt/radarr4k/Radarr
  register: subfolder1

- name: Check subfolder2 exists
  stat:
    path: /opt/radarr4k/app
  register: subfolder2

- name: Move 'radarr4k' folder contents to 'app' subfolder
  shell: |
    mv /opt/radarr4k /tmp/app
    mkdir /opt/radarr4k
    mv /tmp/app /opt/radarr4k/
    find /opt/radarr4k/* -type d -empty -delete
    chown -R {{user}}:{{user}} /opt/radarr4k
  when: not (subfolder1.stat.exists or subfolder2.stat.exists)

- name: Move 'Radarr' subfolder to 'app' subfolder
  shell: |
    mv /opt/radarr4k/Radarr /opt/radarr4k/app
    chown -R {{user}}:{{user}} /opt/radarr4k
  when: (subfolder1.stat.exists) and (not subfolder2.stat.exists)

- name: Create and start container
  docker_container:
    name: radarr4k
    image: hotio/suitarr:radarr
    pull: yes
    published_ports:
      - "7879:7878"
    env:
      VERSION: "unstable"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      BACKUP: "no"
    labels:
      traefik.enable: "true"
      traefik.backend: "radarr4k"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:radarr4k.{{domain}}"
      traefik.port: "7879"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/radarr4k:/config"
      - /mnt/unionfs/Media:/data
      - "/mnt/unionfs/Media/Full HD Movies:/movies"
      - "/mnt:/mnt"
      - "/opt/scripts:/scripts"
      - "{{downloads.nzbs}}:/downloads/nzbs"
      - "{{downloads.torrents}}:/downloads/torrents"
    networks:
      - name: cloudbox
        aliases:
          - radarr4k
    restart_policy: always
    state: started

- name: Remove bridge network
  shell: "docker network disconnect -f bridge radarr4k"
  ignore_errors: yes
