#########################################################################
# Title:         Cloudbox: ZNC Role                                     #
# Author(s):     L3uddz, Horjulf                                        #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  horjulf/docker-znc                                     #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: znc

- name: Stop and remove any existing container
  docker_container:
    name: znc
    state: absent

- name: Create znc directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/znc

- name: Create and start container
  docker_container:
    name: znc
    image: horjulf/docker-znc
    pull: yes
    published_ports:
      - "6501:6501"
      - "6502:6502"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
    labels:
      traefik.enable: "true"
      traefik.backend: "znc"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:znc.{{domain}}"
      traefik.port: "6501"
      traefik.docker.network: "cloudbox"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/znc:/config"
    networks:
      - name: cloudbox
        aliases:
          - znc
    purge_networks: yes
    restart_policy: always
    state: started
